### PR TITLE
Use remove-trailing-separator dependency (closes #3)

### LINKED ISSUE #3: Use `remove-trailing-separator` module as dependency?
Was thinking it might be better to use that module as a dependency instead of the regexp.

Ref https://github.com/darsain/remove-trailing-separator

### PR DESCRIPTION
**Pull request by phated**
As requested 😃

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks! I appreciate the additional unit tests too!

**Comment by jonschlinkert** [comment]
published and released as 2.1.0, thanks again!

**Comment by phated** [comment]
You rock!  Do you want to add me as collab here?

**Comment by jonschlinkert** [comment]
absolutely! was just about to do that, almost beat you to the question!

**Comment by jonschlinkert** [comment]
done, added you as a collab here and owner on npm

**Pull request merged**
