### PR TITLE
Update mocha to avoid vulnerabilities

### PR DESCRIPTION
**Pull request by vulpivia**

### CODE REVIEW

**Comment by phated** [comment]
Dev Dependencies don't cause security vulnerabilities in your code. `npm` doesn't install them when you install this project.

**Comment by vulpivia** [comment]
Yes, it is less problematic as it only affects people who work directly on this package, but I see no reason to use a 3 year old version instead of the current one. All tests still work.

**Comment by phated** [comment]
Unfortunately they don't: https://travis-ci.org/github/jonschlinkert/normalize-path/builds/675181819

Changing the build matrix is a breaking change because you no longer test those older versions of the platform.

We'll consider this upgrade when we are ready for a major (breaking) release.

**Comment by vulpivia** [comment]
Okay, that's definitely a valid reason then. Thanks for the Travis CI link.

**Comment by phated** [comment]
👍 sorry that the PR didn't have the run attached. It seems like github is acting up a bit.

**Pull request closed without merging**
